# default configuration
baseURL = "https://ntutiae.org/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "北科大 智慧自動化工程科"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2

[[menu.main]]
URL = "courses"
name = "課程總覽"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = "/images/IAE/nav_img.png"
IAE_logo = "/images/IAE/LOGO.png"
# theme color
theme_color = "#41228e"
# contact info
phone = "886-2-27712171#4853"
email = "a4853@ntut.edu.tw"
instagram = "@ntut_iae"
instagram_link = "https://instagram.com/ntut_iae?utm_medium=copy_link"
address = "10608 臺北市忠孝東路三段1號 綜合科館708室"
department_chname = "國立臺北科技大學五年制專科部智慧自動化工程科"
department_engname = "Department of Intelligent Automation Engineering"
# meta description
author = "Johnathan Smith"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# baidu site verification
baidu_site_verification = "" #Your verification code
# baidu analytics
baidu_analytics_id = "" #Your ID
# copyright
copyright = "Copyright &copy; 2021 a Theme by [Gethugothemes](https://gethugothemes.com)"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader_IAE.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = false
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "25.043377959894013"
map_longitude = "121.53768849146095"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-instagram"
URL = "#"

[[params.social]]
icon = "ti-dribbble"
URL = "#"

[[params.social]]
icon = "ti-twitter-alt"
URL = "#"
